// array holding translation strings for used in javascript code
// translated key/value pairs are generated by Smarty templates
_translations = Array();

// $.ajaxSetup({cache: false});

$(document).bind('mobileinit', function() {
	$.mobile.selectmenu.prototype.options.nativeMenu = false;
});

$('[data-role="page"]').live('pageshow', function() {
	var url = location.hash;
	if (url.length > 0) {
		url = url.substr(1);
	} else {
		url = location.href;
	}
	// update the language form action URL
	$('#langForm').attr('action', url);

	// update the "Go to Standard View" href
	var match = url.match(/([&?]?ui=[^&]+)/);
	if (match) {
		var replace = ((match[1].indexOf('?') != -1) ? '?' : '&') + 'ui=standard';
		url = url.replace(match[1], replace);
	} else {
		url += ((url.indexOf('?') == -1) ? '?' : '&') + 'ui=standard';
	}
	url = url.replace('&ui-state=dialog', '');
	$('a.standard-view').each(function() {
		$(this).attr('href', url);
	});
});

function pwdToText(fieldId){
	var elem = document.getElementById(fieldId);
	var input = document.createElement('input');
	input.id = elem.id;
	input.name = elem.name;
	input.value = elem.value;
	input.size = elem.size;
	input.onfocus = elem.onfocus;
	input.onblur = elem.onblur;
	input.className = elem.className;
	if (elem.type == 'text' ){
		input.type = 'password';
	} else {
		input.type = 'text'; 
	}

	elem.parentNode.replaceChild(input, elem);
	return input;
}

function moreFacets(name){
	$("#more" + name).hide();
	$(".narrowGroupHidden_" + name).show();
}
function lessFacets(name){
	$("#more" + name).show();
	$(".narrowGroupHidden_" + name).hide();
}

var ajaxCallback = null;
function ajaxLogin(callback){
	ajaxCallback = callback;
	ajaxLightbox(path + '/MyResearch/AJAX?method=LoginForm');
}

function ajaxLightbox(urlToLoad, parentId, left, width, top, height){
	$.mobile.changePage( urlToLoad, {
		type: "get",
		role  : "dialog",
		showLoadMsg: true
	});
}

function hideLightbox(){
	$('.ui-dialog').dialog('close');
}

function processAjaxLogin(){
	var username = $("#username").val();
	var password = $("#password").val();
	if (!username || !password){
		alert("Please enter both the username and password");
		return false;
	}
	var url = path + "/AJAX/JSON?method=loginUser"
	$.ajax({url: url,
			data: {username: username, password: password},
			success: function(response){
				if (response.result.success == true){
					loggedIn = true;
					// Hide "log in" options and show "log out" options:
					$('.loginOptions').hide();
					$('.logoutOptions').show();
					$('#loginOptions').hide();
					$('#logoutOptions').show();
					$('#myAccountNameLink').html(response.result.name);
					hideLightbox();
					if (ajaxCallback  && typeof(ajaxCallback) === "function"){
						ajaxCallback();
					}
				}else{
					alert("That login information was not recognized.  Please try again.");
				}
			},
			error: function(){
				alert("There was an error processing your login, please try again.");
			},
			dataType: 'json',
			type: 'post' 
	});
	
	return false;
}

function showProcessingIndicator(message){
	if (message != undefined){
		$.mobile.loadingMessage = message;
	}
	$.mobile.showPageLoadingMsg();
}

function getQuerystringParameters(){
	var vars = [];
	var q = document.URL.split('?')[1];
	if(q != undefined){
		q = q.split('&');
		for(var i = 0; i < q.length; i++){
			var hash = q[i].split('=');
			vars[hash[0]] = hash[1];
		}
	}
	return vars;
}